[package]
name = "demo-object-detection"
version = "0.1.0"
edition = "2021"

[dependencies]
wasi-nn = "0.4.0"
mediapipe-rs = { git = "https://github.com/WasmEdge/mediapipe-rs.git",rev = "68462d2" }
image = { version = "0.24", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "farbfeld"] }
