name: Build and Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root
    steps:
    - uses: actions/checkout@v2

    - name: install curl and rust
      run: ./scripts/rust-init.sh

    - name: init wasmedge environment
      run: ./scripts/wasmedge-init.sh

    - name: Install Rust target for wasm
      run: |
        rustup target add wasm32-wasi

    - name: init ffmpeg dependencies
      run: ./scripts/ffmpeg-deps-init.sh
    - name: Example
      run: |
        cargo build --target wasm32-wasi --release
        wasmedge compile target/wasm32-wasi/release/demo-object-detection.wasm demo-object-detection.wasm
        wasmedge --dir .:. demo-object-detection.wasm example.jpg output.jpg

    - uses: actions/upload-artifact@v3
      with:
        name: Output
        path: |
          demo-object-detection.wasm
          output.jpg
